# Generated by Django 3.0.6 on 2020-05-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('First_Name', models.CharField(max_length=15, unique=True)),
                ('Last_Name', models.CharField(max_length=15, unique=True)),
                ('Email', models.EmailField(max_length=25, unique=True)),
                ('Contact', models.CharField(max_length=10, unique=True)),
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=18)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6)),
                ('City', models.CharField(choices=[('Mumbai', 'Mumbai'), ('Chennai', 'Chennai'), ('Delhi', 'Delhi'), ('Kolkata', 'Kolkata'), ('Banglore', 'Banglore'), ('Indore', 'Indore'), ('Hyderabad', 'Hyderabad'), ('Ahmedbad', 'Ahmedbad'), ('Amritsar', 'Amritsar'), ('Jaipur', 'Jaipur')], max_length=10)),
                ('Address_Line_1', models.CharField(max_length=50)),
                ('Address_Line_2', models.CharField(max_length=50)),
                ('PinCode', models.CharField(max_length=6)),
            ],
        ),
    ]
